### ISSUE TITLE
内存泄露

### ISSUE THREAD

**Issue by blacktrain** [astrotycoon/sys-queue.h#1]
line 48:
TAILQ_REMOVE(&head, data5, tailq_entry);  
并不会释放
line 39:
struct _Data *data5 = (struct _Data *)calloc(1, sizeof(struct _Data)); 
申请的内存，TAILQ_REMOVE只是从队列中删除节点，参见:
sys/queue.h TAILQ_REMOVE的定义：

#define	TAILQ_REMOVE(head, elm, field) do {				\
	if (((elm)->field.tqe_next) != NULL)				\
		(elm)->field.tqe_next->field.tqe_prev = 		\
		    (elm)->field.tqe_prev;				\
	else								\
		(head)->tqh_last = (elm)->field.tqe_prev;		\
	*(elm)->field.tqe_prev = (elm)->field.tqe_next;			\
} while (/*CONSTCOND*/0)

**Comment by astrotycoon** [comment]
thx
